name: flutter_ladder
description: "A step-by-step Flutter learning app with interactive coding"
publish_to: "none"
version: 1.0.0+1
license: MIT

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.0.0

  flutter_web_plugins:
    sdk: flutter

dev_dependencief:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
