name: flutter_ladder
description: "A step-by-step Flutter learning app with interactive coding"
publish_to: "none"
version: 1.0.0+1
license: MIT

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.0.0

  flutter_web_plugins:
    sdk: flutter
  http: ^1.4.0
  flutter_code_editor: ^0.3.4
  code_text_field: ^1.1.0
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencief:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
